sims/nic/smartnic_adapter/smartnic_adapter.o: \
 sims/nic/smartnic_adapter/smartnic_adapter.c lib/simbricks/pcie/if.h \
 lib/simbricks/base/generic.h lib/simbricks/base/if.h \
 lib/simbricks/base/proto.h lib/simbricks/pcie/proto.h \
 lib/simbricks/pcieadapter/pcieadapter.h \
 lib/simbricks/smartnicif/smartnicif.h
lib/simbricks/pcie/if.h:
lib/simbricks/base/generic.h:
lib/simbricks/base/if.h:
lib/simbricks/base/proto.h:
lib/simbricks/pcie/proto.h:
lib/simbricks/pcieadapter/pcieadapter.h:
lib/simbricks/smartnicif/smartnicif.h:
